name: Build Typst PDF

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Typst
        uses: typst-community/setup-typst@v5

      - name: Build PDF
        run: typst compile docs/weblab-documentation.typ weblab-documentation.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: weblab-documentation
          path: weblab-documentation.pdf

      - name: Publish documentation
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: Architektur Dokumentation
          files: weblab-documentation.pdf
          overwrite_files: true
          prerelease: false
          make_latest: true
